"""Run multi-user scaling experiments and aggregate paper-style figures.

The suite trains/evaluates the same method set at several user counts:

    HAN+MAPPO, Attn+MAPPO, MAPPO, MADDPG, PDQN, and rule-based baselines.

Each user count keeps its own training and comparison directory. The final
aggregation reads the standard comparison artifacts generated by
scripts/compare_system_baselines.py and creates cross-user scaling figures.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shlex
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional, Sequence

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PYTHON = sys.executable
DEFAULT_USER_COUNTS = (20, 25, 30, 35, 40)
DEFAULT_BASELINES = (
    "attn_mappo",
    "mappo_no_han",
    "maddpg",
    "pdqn",
    "han_maddpg",
    "han_pdqn",
    "random",
    "min_distance",
    "full_local",
    "joint_greedy",
)
TRAIN_ARTIFACTS = ("training_history.json", "best_model.pt", "final_model.pt")
METHOD_DISPLAY_NAMES = {
    "han_mappo": "HAN+MAPPO",
    "attn_mappo": "Attn+MAPPO",
    "mappo_no_han": "MAPPO",
    "maddpg": "MADDPG",
    "pdqn": "PDQN",
    "han_maddpg": "HAN+MADDPG",
    "han_pdqn": "HAN+PDQN",
    "random": "Random",
    "min_distance": "Min-Distance",
    "full_local": "Full-Local",
    "joint_greedy": "Joint Greedy",
}
LEARNED_REWARD_METHODS = (
    "han_mappo",
    "attn_mappo",
    "mappo_no_han",
    "maddpg",
    "pdqn",
    "han_maddpg",
    "han_pdqn",
)
CORE_SCALING_METRICS = (
    ("avg_delay", "Average Delay", "Average Delay (s)", 1.0),
    ("task_success_rate", "Task Success Rate", "Task Success Rate (%)", 100.0),
    ("deadline_violation_rate", "Deadline Violation Rate", "Deadline Violation Rate (%)", 100.0),
    ("service_continuity_rate", "Service Continuity Rate", "Service Continuity Rate (%)", 100.0),
)
RESOURCE_SCALING_METRICS = (
    ("mec_load_fairness", "MEC Load Fairness", "MEC Load Fairness", 1.0),
    ("energy_per_successful_task", "Energy per Successful Task", "Energy per Successful Task", 1.0),
)


@dataclass(frozen=True)
class SuitePaths:
    suite_dir: Path
    system_run_dir: Path
    compare_output_dir: Path
    log_dir: Path


@dataclass(frozen=True)
class MultiUserConfig:
    run_id: str
    user_counts: tuple[int, ...] = DEFAULT_USER_COUNTS
    python_executable: str = DEFAULT_PYTHON
    seed: int = 42
    device: str = "auto"
    total_timesteps: int = 300_000
    max_steps: int = 600
    n_steps: int = 1024
    eval_interval: int = 50_000
    eval_episodes: int = 3
    save_interval: int = 100_000
    graph_update_interval: int = 1
    log_interval: int = 1
    best_model_metric: str = "avg_delay"
    compare_ranking_metric: str = "avg_delay"
    compare_episodes: int = 3
    plot_window: int = 5
    early_stop_patience: int = 0
    baselines: tuple[str, ...] = DEFAULT_BASELINES
    skip_system_train: bool = False
    skip_compare: bool = False
    force_system_train: bool = False
    reuse_learned_checkpoints: bool = False
    aggregate_only: bool = False
    dry_run: bool = False


def resolve_run_id(run_id: Optional[str] = None, now: Optional[datetime] = None) -> str:
    if run_id:
        return run_id
    return (now or datetime.now()).strftime("%Y%m%d_%H%M%S")


def build_paths(project_root: Path, run_id: str, num_users: int) -> SuitePaths:
    results_dir = project_root / "results"
    suite_dir = results_dir / "baseline_compare" / f"multiuser_scaling_{run_id}"
    return SuitePaths(
        suite_dir=suite_dir,
        system_run_dir=results_dir / f"full_train_latency_priority_multiuser_u{num_users}_{run_id}",
        compare_output_dir=suite_dir / f"u{num_users}",
        log_dir=results_dir / "logs",
    )


def _path_arg(path: Path) -> str:
    return str(path)


def build_train_command(paths: SuitePaths, config: MultiUserConfig, num_users: int) -> list[str]:
    return [
        config.python_executable,
        "scripts/train.py",
        "--exp_name",
        f"han_mappo_latency_priority_multiuser_u{num_users}",
        "--algorithm",
        "mappo",
        "--seed",
        str(config.seed),
        "--device",
        config.device,
        "--num_users",
        str(num_users),
        "--total_timesteps",
        str(config.total_timesteps),
        "--max_steps",
        str(config.max_steps),
        "--n_steps",
        str(config.n_steps),
        "--eval_interval",
        str(config.eval_interval),
        "--eval_episodes",
        str(config.eval_episodes),
        "--save_interval",
        str(config.save_interval),
        "--graph_update_interval",
        str(config.graph_update_interval),
        "--log_interval",
        str(config.log_interval),
        "--best-model-metric",
        config.best_model_metric,
        "--save_path",
        _path_arg(paths.system_run_dir),
        "--log_path",
        _path_arg(paths.log_dir),
    ]


def build_compare_command(paths: SuitePaths, config: MultiUserConfig, num_users: int) -> list[str]:
    command = [
        config.python_executable,
        "scripts/compare_system_baselines.py",
        "--run-mode",
        "compare_only",
        "--system-run-dir",
        _path_arg(paths.system_run_dir),
        "--output-dir",
        _path_arg(paths.compare_output_dir),
        "--episodes",
        str(config.compare_episodes),
        "--max-steps",
        str(config.max_steps),
        "--total-timesteps",
        str(config.total_timesteps),
        "--seed",
        str(config.seed),
        "--device",
        config.device,
        "--num-users",
        str(num_users),
        "--best-model-metric",
        config.best_model_metric,
        "--compare-ranking-metric",
        config.compare_ranking_metric,
        "--plot-window",
        str(config.plot_window),
        "--early-stop-patience",
        str(config.early_stop_patience),
        "--baselines",
    ]
    command.extend(config.baselines)
    if config.reuse_learned_checkpoints:
        command.append("--reuse-learned-checkpoints")
    return command


def has_training_artifacts(run_dir: Path) -> bool:
    return any((run_dir / filename).exists() for filename in TRAIN_ARTIFACTS)


def format_command(command: Sequence[str]) -> str:
    return " ".join(shlex.quote(part) for part in command)


def run_command(command: Sequence[str], cwd: Path, log_path: Path, dry_run: bool) -> None:
    command_text = format_command(command)
    print(command_text, flush=True)
    if dry_run:
        return

    log_path.parent.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ)
    env["PYTHONUNBUFFERED"] = "1"
    with log_path.open("a", encoding="utf-8") as log_file:
        log_file.write(f"\n$ {command_text}\n")
        log_file.flush()
        process = subprocess.Popen(
            list(command),
            cwd=cwd,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="")
            log_file.write(line)
        return_code = process.wait()
        if return_code != 0:
            raise subprocess.CalledProcessError(return_code, command)


def method_display_name(method: str, fallback: str = "") -> str:
    if method in METHOD_DISPLAY_NAMES:
        return METHOD_DISPLAY_NAMES[method]
    if fallback and fallback in METHOD_DISPLAY_NAMES.values():
        return fallback
    return fallback or method


def _read_comparison_rows(summary_csv: Path, num_users: int) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with summary_csv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            method = row.get("method", "")
            normalized = dict(row)
            normalized["num_users"] = str(num_users)
            normalized["display_name"] = method_display_name(method, row.get("display_name", ""))
            rows.append(normalized)
    return rows


def aggregate_user_summaries(
    suite_dir: Path,
    user_counts: Sequence[int],
) -> tuple[list[dict[str, str]], Path]:
    rows: list[dict[str, str]] = []
    for num_users in user_counts:
        summary_csv = suite_dir / f"u{num_users}" / "comparison_summary.csv"
        if not summary_csv.exists():
            raise FileNotFoundError(f"Missing comparison summary: {summary_csv}")
        rows.extend(_read_comparison_rows(summary_csv, num_users))

    fieldnames: list[str] = ["num_users", "method", "display_name"]
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)

    output_csv = suite_dir / "multiuser_summary.csv"
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    return rows, output_csv


def _float_or_none(value: object) -> Optional[float]:
    try:
        if value is None or value == "":
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _method_order(rows: Sequence[dict[str, str]]) -> list[str]:
    preferred = list(METHOD_DISPLAY_NAMES.values())
    present = {row.get("display_name", "") for row in rows}
    ordered = [name for name in preferred if name in present]
    ordered.extend(sorted(name for name in present if name and name not in ordered))
    return ordered


def setup_plot_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "DejaVu Serif"],
            "font.size": 11,
            "axes.titlesize": 12,
            "axes.labelsize": 11,
            "legend.fontsize": 9,
            "lines.linewidth": 1.8,
            "lines.markersize": 5,
            "figure.dpi": 220,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
            "axes.grid": True,
            "grid.alpha": 0.45,
            "grid.linestyle": "--",
        }
    )


def plot_scaling_metrics(
    rows: Sequence[dict[str, str]],
    suite_dir: Path,
    metric_specs: Sequence[tuple[str, str, str, float]],
    filename: str,
) -> Optional[Path]:
    if not rows:
        return None
    setup_plot_style()
    cols = 2
    metric_count = len(metric_specs)
    rows_count = (metric_count + cols - 1) // cols
    fig, axes = plt.subplots(rows_count, cols, figsize=(11, 4.2 * rows_count), squeeze=False)
    method_names = _method_order(rows)
    markers = ["o", "s", "^", "D", "v", "P", "X", "*", "h"]

    for ax, (metric_key, title, ylabel, scale) in zip(axes.flat, metric_specs):
        for index, display_name in enumerate(method_names):
            method_rows = [
                row for row in rows
                if row.get("display_name") == display_name and _float_or_none(row.get(metric_key)) is not None
            ]
            method_rows.sort(key=lambda row: int(row["num_users"]))
            if not method_rows:
                continue
            x_values = [int(row["num_users"]) for row in method_rows]
            y_values = [float(row[metric_key]) * scale for row in method_rows]
            ax.plot(
                x_values,
                y_values,
                marker=markers[index % len(markers)],
                label=display_name,
            )
        ax.set_title(title)
        ax.set_xlabel("Number of Users")
        ax.set_ylabel(ylabel)
        ax.set_xticks(sorted({int(row["num_users"]) for row in rows}))

    for ax in axes.flat[metric_count:]:
        ax.axis("off")

    handles, labels = axes.flat[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="upper center", ncol=min(5, len(labels)), frameon=True)
        fig.subplots_adjust(top=0.88)
    output_path = suite_dir / filename
    fig.savefig(output_path)
    plt.close(fig)
    return output_path


def _load_training_curve(history_path: Path) -> tuple[list[float], list[float]]:
    if not history_path.exists():
        return [], []
    with history_path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    steps: list[float] = []
    rewards: list[float] = []
    for record in payload.get("training", []):
        reward = _float_or_none(record.get("mean_reward", record.get("reward")))
        step = _float_or_none(record.get("total_steps", record.get("step")))
        if reward is None or step is None:
            continue
        steps.append(step)
        rewards.append(reward)
    return steps, rewards


def training_history_path(paths: SuitePaths, method: str) -> Path:
    if method == "han_mappo":
        return paths.system_run_dir / "training_history.json"
    return paths.compare_output_dir / "learned_baselines" / method / "training_history.json"


def plot_reward_convergence(
    project_root: Path,
    run_id: str,
    user_counts: Sequence[int],
    suite_dir: Path,
) -> Optional[Path]:
    setup_plot_style()
    fig, axes = plt.subplots(1, len(user_counts), figsize=(5.2 * len(user_counts), 4.2), squeeze=False)
    plotted_any = False
    markers = ["o", "s", "^", "D", "v"]

    for axis_index, num_users in enumerate(user_counts):
        ax = axes.flat[axis_index]
        paths = build_paths(project_root, run_id, num_users)
        for method_index, method in enumerate(LEARNED_REWARD_METHODS):
            history_path = training_history_path(paths, method)
            steps, rewards = _load_training_curve(history_path)
            if not steps:
                continue
            plotted_any = True
            ax.plot(
                steps,
                rewards,
                marker=markers[method_index % len(markers)],
                markevery=max(len(steps) // 8, 1),
                label=method_display_name(method),
            )
        ax.set_title(f"U{num_users}")
        ax.set_xlabel("Training Steps")
        ax.set_ylabel("Mean Episode Reward")

    handles, labels = axes.flat[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="upper center", ncol=min(5, len(labels)), frameon=True)
        fig.subplots_adjust(top=0.82)

    if not plotted_any:
        plt.close(fig)
        return None
    output_path = suite_dir / "multiuser_reward_convergence.png"
    fig.savefig(output_path)
    plt.close(fig)
    return output_path


def write_manifest(
    suite_dir: Path,
    config: MultiUserConfig,
    generated_paths: Iterable[Path],
) -> Path:
    manifest_path = suite_dir / "suite_manifest.json"
    payload = {
        "run_id": config.run_id,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "config": asdict(config),
        "method_display_names": METHOD_DISPLAY_NAMES,
        "generated_artifacts": [str(path) for path in generated_paths],
    }
    with manifest_path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
    return manifest_path


def generate_aggregate_artifacts(
    project_root: Path,
    config: MultiUserConfig,
    suite_dir: Path,
) -> list[Path]:
    summary_rows, summary_csv = aggregate_user_summaries(suite_dir, config.user_counts)
    generated: list[Path] = [summary_csv]

    reward_plot = plot_reward_convergence(project_root, config.run_id, config.user_counts, suite_dir)
    if reward_plot is not None:
        generated.append(reward_plot)
    core_plot = plot_scaling_metrics(
        summary_rows,
        suite_dir,
        CORE_SCALING_METRICS,
        "multiuser_core_metrics.png",
    )
    if core_plot is not None:
        generated.append(core_plot)
    resource_plot = plot_scaling_metrics(
        summary_rows,
        suite_dir,
        RESOURCE_SCALING_METRICS,
        "multiuser_resource_metrics.png",
    )
    if resource_plot is not None:
        generated.append(resource_plot)
    manifest = write_manifest(suite_dir, config, generated)
    generated.append(manifest)
    return generated


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run user-count scaling experiments for HAN+MAPPO and comparison baselines."
    )
    parser.add_argument("--run-id", type=str, default=None)
    parser.add_argument("--user-counts", type=int, nargs="+", default=list(DEFAULT_USER_COUNTS))
    parser.add_argument("--python-executable", type=str, default=DEFAULT_PYTHON)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--total-timesteps", type=int, default=300_000)
    parser.add_argument("--max-steps", type=int, default=600)
    parser.add_argument("--n-steps", type=int, default=1024)
    parser.add_argument("--eval-interval", type=int, default=50_000)
    parser.add_argument("--eval-episodes", type=int, default=3)
    parser.add_argument("--save-interval", type=int, default=100_000)
    parser.add_argument(
        "--graph-update-interval",
        "--graph_update_interval",
        dest="graph_update_interval",
        type=int,
        default=1,
    )
    parser.add_argument("--compare-episodes", type=int, default=3)
    parser.add_argument("--plot-window", type=int, default=5)
    parser.add_argument("--early-stop-patience", type=int, default=0)
    parser.add_argument("--best-model-metric", type=str, default="avg_delay")
    parser.add_argument("--compare-ranking-metric", type=str, default="avg_delay")
    parser.add_argument("--baselines", nargs="+", default=list(DEFAULT_BASELINES))
    parser.add_argument("--force-system-train", action="store_true")
    parser.add_argument("--skip-system-train", action="store_true")
    parser.add_argument("--skip-compare", action="store_true")
    parser.add_argument("--reuse-learned-checkpoints", action="store_true")
    parser.add_argument(
        "--aggregate-only",
        action="store_true",
        help="Only rebuild suite-level CSV, figures, and manifest from existing u*/comparison_summary.csv files.",
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args(argv)


def config_from_args(args: argparse.Namespace) -> MultiUserConfig:
    return MultiUserConfig(
        run_id=resolve_run_id(args.run_id),
        user_counts=tuple(args.user_counts),
        python_executable=args.python_executable,
        seed=args.seed,
        device=args.device,
        total_timesteps=args.total_timesteps,
        max_steps=args.max_steps,
        n_steps=args.n_steps,
        eval_interval=args.eval_interval,
        eval_episodes=args.eval_episodes,
        save_interval=args.save_interval,
        graph_update_interval=args.graph_update_interval,
        best_model_metric=args.best_model_metric,
        compare_ranking_metric=args.compare_ranking_metric,
        compare_episodes=args.compare_episodes,
        plot_window=args.plot_window,
        early_stop_patience=args.early_stop_patience,
        baselines=tuple(args.baselines),
        skip_system_train=args.skip_system_train,
        skip_compare=args.skip_compare,
        force_system_train=args.force_system_train,
        reuse_learned_checkpoints=args.reuse_learned_checkpoints,
        aggregate_only=args.aggregate_only,
        dry_run=args.dry_run,
    )


def run_user_count(config: MultiUserConfig, num_users: int) -> SuitePaths:
    paths = build_paths(PROJECT_ROOT, config.run_id, num_users)
    if not config.dry_run:
        paths.log_dir.mkdir(parents=True, exist_ok=True)
        paths.suite_dir.mkdir(parents=True, exist_ok=True)
        paths.compare_output_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n=== Multi-user scaling: U{num_users} ===")
    print(f"System run dir: {paths.system_run_dir}")
    print(f"Compare output dir: {paths.compare_output_dir}")

    train_needed = not config.skip_system_train
    if train_needed and has_training_artifacts(paths.system_run_dir) and not config.force_system_train:
        train_needed = False
        print("Existing HAN+MAPPO artifacts found; reusing system training.")

    if train_needed:
        if not config.dry_run:
            paths.system_run_dir.mkdir(parents=True, exist_ok=True)
        run_command(
            build_train_command(paths, config, num_users),
            PROJECT_ROOT,
            paths.suite_dir / f"u{num_users}_system_train.log",
            config.dry_run,
        )
    else:
        print("System training step skipped.")

    if not config.skip_compare:
        if not config.dry_run and not has_training_artifacts(paths.system_run_dir):
            raise FileNotFoundError(
                f"No HAN+MAPPO artifacts found in {paths.system_run_dir}. "
                "Run without --skip-system-train first, or reuse an existing run id."
            )
        run_command(
            build_compare_command(paths, config, num_users),
            PROJECT_ROOT,
            paths.suite_dir / f"u{num_users}_compare.log",
            config.dry_run,
        )
    else:
        print("Comparison step skipped.")
    return paths


def main() -> None:
    config = config_from_args(parse_args())
    print(f"Run id: {config.run_id}")
    print(f"User counts: {', '.join(str(count) for count in config.user_counts)}")
    print(f"Baselines: {', '.join(config.baselines)}")

    suite_dir = build_paths(PROJECT_ROOT, config.run_id, config.user_counts[0]).suite_dir
    if config.aggregate_only:
        generated = generate_aggregate_artifacts(PROJECT_ROOT, config, suite_dir)
        summary_csv = suite_dir / "multiuser_summary.csv"
        print(f"Multi-user summary CSV: {summary_csv}")
        for artifact in generated:
            print(f"Generated artifact: {artifact}")
        return

    first_paths: Optional[SuitePaths] = None
    for num_users in config.user_counts:
        paths = run_user_count(config, num_users)
        first_paths = first_paths or paths

    if config.dry_run or config.skip_compare:
        print("Aggregation skipped.")
        return

    assert first_paths is not None
    generated = generate_aggregate_artifacts(PROJECT_ROOT, config, first_paths.suite_dir)
    summary_csv = first_paths.suite_dir / "multiuser_summary.csv"

    print(f"Multi-user summary CSV: {summary_csv}")
    for artifact in generated:
        print(f"Generated artifact: {artifact}")


if __name__ == "__main__":
    main()
