"""Run multi-user scaling experiments and aggregate paper-style figures.

The suite trains/evaluates the same method set at several user counts:

    HAN+MAPPO, Attn+MAPPO, MAPPO, MADDPG, PDQN, and rule-based baselines.

Each user count keeps its own training and comparison directory. The final
aggregation reads the standard comparison artifacts generated by
scripts/compare_system_baselines.py and creates cross-user scaling figures.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import shlex
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, Optional, Sequence

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.paper_metrics import (
    COMBINED_SCALING_METRICS,
    CORE_SCALING_METRICS,
    RESOURCE_SCALING_METRICS,
    SUCCESS_DEPENDENT_METRICS,
    bootstrap_mean_ci,
    derive_paper_metrics,
)
from scripts.train import ENVIRONMENT_SCHEMA_VERSION, TrainConfig


DEFAULT_PYTHON = sys.executable
DEFAULT_USER_COUNTS = (20, 25, 30, 35, 40)
DEFAULT_BASELINES = (
    "attn_mappo",
    "mappo_no_han",
    "maddpg",
    "pdqn",
    "han_maddpg",
    "han_pdqn",
    "random",
    "min_distance",
    "full_local",
    "joint_greedy",
)
TRAIN_ARTIFACTS = ("training_history.json", "best_model.pt", "final_model.pt")
METHOD_DISPLAY_NAMES = {
    "han_mappo": "HAN+MAPPO",
    "attn_mappo": "Attn+MAPPO",
    "mappo_no_han": "MAPPO",
    "maddpg": "MADDPG",
    "pdqn": "PDQN",
    "han_maddpg": "HAN+MADDPG",
    "han_pdqn": "HAN+PDQN",
    "random": "Random",
    "min_distance": "Min-Distance",
    "full_local": "Full-Local",
    "joint_greedy": "Joint Greedy",
}
LEARNED_REWARD_METHODS = (
    "han_mappo",
    "attn_mappo",
    "mappo_no_han",
    "maddpg",
    "pdqn",
    "han_maddpg",
    "han_pdqn",
)
REWARD_CONFIG_KEYS = (
    "reward_delay_weight",
    "reward_energy_weight",
    "reward_interruption_weight",
    "reward_failed_handover_penalty",
)


@dataclass(frozen=True)
class SuitePaths:
    suite_dir: Path
    system_run_dir: Path
    compare_output_dir: Path
    log_dir: Path


@dataclass(frozen=True)
class MultiUserConfig:
    run_id: str
    user_counts: tuple[int, ...] = DEFAULT_USER_COUNTS
    python_executable: str = DEFAULT_PYTHON
    seed: int = 42
    seeds: tuple[int, ...] = ()
    device: str = "auto"
    total_timesteps: int = 300_000
    max_steps: int = 600
    n_steps: int = 1024
    eval_interval: int = 50_000
    eval_episodes: int = 3
    save_interval: int = 100_000
    graph_update_interval: int = 1
    log_interval: int = 1
    best_model_metric: str = "avg_delay"
    compare_ranking_metric: str = "avg_delay"
    compare_episodes: int = 3
    plot_window: int = 5
    early_stop_patience: int = 0
    baselines: tuple[str, ...] = DEFAULT_BASELINES
    skip_system_train: bool = False
    skip_compare: bool = False
    force_system_train: bool = False
    reuse_learned_checkpoints: bool = False
    aggregate_only: bool = False
    include_methods: tuple[str, ...] = ()
    output_suffix: str = ""
    dry_run: bool = False


def resolve_run_id(run_id: Optional[str] = None, now: Optional[datetime] = None) -> str:
    if run_id:
        return run_id
    return (now or datetime.now()).strftime("%Y%m%d_%H%M%S")


def effective_seeds(config: MultiUserConfig) -> tuple[int, ...]:
    return config.seeds or (config.seed,)


def build_paths(
    project_root: Path,
    run_id: str,
    num_users: int,
    seed: Optional[int] = None,
    multi_seed: bool = False,
) -> SuitePaths:
    results_dir = project_root / "results"
    suite_dir = results_dir / "baseline_compare" / f"multiuser_scaling_{run_id}"
    system_run_dir = results_dir / f"full_train_latency_priority_multiuser_u{num_users}_{run_id}"
    compare_output_dir = suite_dir / f"u{num_users}"
    if multi_seed and seed is not None:
        system_run_dir = system_run_dir / f"seed_{seed}"
        compare_output_dir = compare_output_dir / f"seed_{seed}"
    return SuitePaths(
        suite_dir=suite_dir,
        system_run_dir=system_run_dir,
        compare_output_dir=compare_output_dir,
        log_dir=results_dir / "logs",
    )


def _path_arg(path: Path) -> str:
    return str(path)


def build_train_command(
    paths: SuitePaths,
    config: MultiUserConfig,
    num_users: int,
    seed: Optional[int] = None,
) -> list[str]:
    run_seed = config.seed if seed is None else seed
    return [
        config.python_executable,
        "scripts/train.py",
        "--exp_name",
        f"han_mappo_latency_priority_multiuser_u{num_users}",
        "--algorithm",
        "mappo",
        "--seed",
        str(run_seed),
        "--device",
        config.device,
        "--num_users",
        str(num_users),
        "--total_timesteps",
        str(config.total_timesteps),
        "--max_steps",
        str(config.max_steps),
        "--n_steps",
        str(config.n_steps),
        "--eval_interval",
        str(config.eval_interval),
        "--eval_episodes",
        str(config.eval_episodes),
        "--save_interval",
        str(config.save_interval),
        "--graph_update_interval",
        str(config.graph_update_interval),
        "--log_interval",
        str(config.log_interval),
        "--best-model-metric",
        config.best_model_metric,
        "--save_path",
        _path_arg(paths.system_run_dir),
        "--log_path",
        _path_arg(paths.log_dir),
    ]


def build_compare_command(
    paths: SuitePaths,
    config: MultiUserConfig,
    num_users: int,
    seed: Optional[int] = None,
) -> list[str]:
    run_seed = config.seed if seed is None else seed
    command = [
        config.python_executable,
        "scripts/compare_system_baselines.py",
        "--run-mode",
        "compare_only",
        "--system-run-dir",
        _path_arg(paths.system_run_dir),
        "--output-dir",
        _path_arg(paths.compare_output_dir),
        "--episodes",
        str(config.compare_episodes),
        "--max-steps",
        str(config.max_steps),
        "--total-timesteps",
        str(config.total_timesteps),
        "--seed",
        str(run_seed),
        "--device",
        config.device,
        "--num-users",
        str(num_users),
        "--best-model-metric",
        config.best_model_metric,
        "--compare-ranking-metric",
        config.compare_ranking_metric,
        "--plot-window",
        str(config.plot_window),
        "--early-stop-patience",
        str(config.early_stop_patience),
        "--baselines",
    ]
    command.extend(config.baselines)
    if config.reuse_learned_checkpoints:
        command.append("--reuse-learned-checkpoints")
    return command


def has_any_training_artifacts(run_dir: Path) -> bool:
    return any((run_dir / filename).exists() for filename in TRAIN_ARTIFACTS)


def has_training_artifacts(
    run_dir: Path,
    *,
    config: Optional[MultiUserConfig] = None,
    num_users: Optional[int] = None,
    seed: Optional[int] = None,
) -> bool:
    final_model = run_dir / "final_model.pt"
    history_path = run_dir / "training_history.json"
    if not final_model.exists() or not history_path.exists():
        return False
    try:
        with history_path.open("r", encoding="utf-8") as handle:
            history = json.load(handle)
    except (OSError, TypeError, ValueError, json.JSONDecodeError):
        return False
    if int(history.get("environment_schema_version", 0)) != ENVIRONMENT_SCHEMA_VERSION:
        return False

    history_config = history.get("config", {}) or {}
    summary = history.get("summary", {}) or {}
    actual_steps = int(summary.get("total_steps", 0))
    if config is None:
        return actual_steps > 0

    defaults = TrainConfig()
    expected = {
        "total_timesteps": int(config.total_timesteps),
        "max_steps": int(config.max_steps),
        "n_steps": int(config.n_steps),
        "eval_interval": int(config.eval_interval),
        "eval_episodes": int(config.eval_episodes),
        "save_interval": int(config.save_interval),
        "early_stop_patience": int(config.early_stop_patience),
        "graph_update_interval": int(config.graph_update_interval),
        "best_model_metric": str(config.best_model_metric),
        "num_users": int(num_users if num_users is not None else history_config.get("num_users", 0)),
        "seed": int(seed if seed is not None else config.seed),
        **{
            key: float(getattr(defaults, key))
            for key in REWARD_CONFIG_KEYS
        },
    }
    if actual_steps <= 0:
        return False
    if (
        expected["early_stop_patience"] <= 0
        and actual_steps < expected["total_timesteps"]
    ):
        return False
    for key, expected_value in expected.items():
        actual_value = history_config.get(key)
        if isinstance(expected_value, float):
            try:
                if not math.isclose(
                    float(actual_value),
                    expected_value,
                    rel_tol=1e-12,
                    abs_tol=1e-12,
                ):
                    return False
            except (TypeError, ValueError):
                return False
        elif actual_value != expected_value:
            return False
    return True


def format_command(command: Sequence[str]) -> str:
    return " ".join(shlex.quote(part) for part in command)


def run_command(command: Sequence[str], cwd: Path, log_path: Path, dry_run: bool) -> None:
    command_text = format_command(command)
    print(command_text, flush=True)
    if dry_run:
        return

    log_path.parent.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ)
    env["PYTHONUNBUFFERED"] = "1"
    with log_path.open("a", encoding="utf-8") as log_file:
        log_file.write(f"\n$ {command_text}\n")
        log_file.flush()
        process = subprocess.Popen(
            list(command),
            cwd=cwd,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="")
            log_file.write(line)
        return_code = process.wait()
        if return_code != 0:
            raise subprocess.CalledProcessError(return_code, command)


def method_display_name(method: str, fallback: str = "") -> str:
    if method in METHOD_DISPLAY_NAMES:
        return METHOD_DISPLAY_NAMES[method]
    if fallback and fallback in METHOD_DISPLAY_NAMES.values():
        return fallback
    return fallback or method


def _normalize_method_selector(value: str) -> str:
    return value.strip().lower().replace("-", "_").replace(" ", "_")


def normalize_output_suffix(value: str) -> str:
    normalized = value.strip().strip("_").replace("-", "_").replace(" ", "_")
    return "".join(char if char.isalnum() or char == "_" else "_" for char in normalized)


def suffixed_filename(filename: str, output_suffix: str = "") -> str:
    suffix = normalize_output_suffix(output_suffix)
    if not suffix:
        return filename
    path = Path(filename)
    return f"{path.stem}_{suffix}{path.suffix}"


def method_matches_include(row: dict[str, str], include_methods: Sequence[str]) -> bool:
    if not include_methods:
        return True
    allowed = {_normalize_method_selector(method) for method in include_methods}
    method = row.get("method", "")
    display_name = row.get("display_name", "")
    candidates = {
        _normalize_method_selector(method),
        _normalize_method_selector(display_name),
        _normalize_method_selector(method_display_name(method, display_name)),
    }
    return bool(candidates & allowed)


def _validate_comparison_schema(compare_dir: Path) -> tuple[float, ...]:
    summary_json = compare_dir / "comparison_summary.json"
    if not summary_json.exists():
        raise FileNotFoundError(f"Missing comparison summary metadata: {summary_json}")
    with summary_json.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    schema_version = int(payload.get("environment_schema_version", 0))
    if schema_version != 5:
        raise ValueError(
            f"{summary_json} uses environment schema {schema_version}; "
            "paper figures require environment_schema_version=5. Re-run this comparison."
        )
    metric_schema_version = int(payload.get("metric_schema_version", 0))
    if metric_schema_version != 2:
        raise ValueError(
            f"{summary_json} uses metric schema {metric_schema_version}; "
            "paper figures require metric_schema_version=2. Re-run this comparison."
        )
    env_config = payload.get("env_config", {}) or {}
    try:
        return tuple(float(env_config[key]) for key in REWARD_CONFIG_KEYS)
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(
            f"{summary_json} is missing the unified reward configuration: "
            f"{', '.join(REWARD_CONFIG_KEYS)}"
        ) from exc


def _read_comparison_rows(
    summary_csv: Path,
    num_users: int,
    seed: int,
) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with summary_csv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            method = row.get("method", "")
            normalized = {
                key: str(value)
                for key, value in derive_paper_metrics(row).items()
            }
            normalized["num_users"] = str(num_users)
            normalized["seed"] = str(seed)
            normalized["display_name"] = method_display_name(method, row.get("display_name", ""))
            completed_tasks = _float_or_none(normalized.get("completed_tasks"))
            if completed_tasks is None or completed_tasks <= 0.0:
                for metric_key in SUCCESS_DEPENDENT_METRICS:
                    normalized[metric_key] = ""
            rows.append(normalized)
    return rows


def _write_csv(path: Path, rows: Sequence[dict[str, str]]) -> Path:
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    return path


def _aggregate_seed_rows(rows: Sequence[dict[str, str]]) -> list[dict[str, str]]:
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = {}
    for row in rows:
        key = (
            str(row.get("num_users", "")),
            str(row.get("method", "")),
            str(row.get("display_name", "")),
        )
        grouped.setdefault(key, []).append(row)

    aggregated: list[dict[str, str]] = []
    for (num_users, method, display_name), group in grouped.items():
        result: dict[str, str] = {
            "num_users": num_users,
            "method": method,
            "display_name": display_name,
            "seed_count": str(len(group)),
        }
        fieldnames = {
            key
            for row in group
            for key in row
            if key not in {"num_users", "method", "display_name", "seed"}
        }
        for fieldname in sorted(fieldnames):
            values = [
                value
                for row in group
                if (value := _float_or_none(row.get(fieldname))) is not None
            ]
            if values:
                mean, low, high = bootstrap_mean_ci(values)
                result[fieldname] = str(mean)
                result[f"{fieldname}_ci_low"] = str(low)
                result[f"{fieldname}_ci_high"] = str(high)
                if fieldname in SUCCESS_DEPENDENT_METRICS:
                    result[f"{fieldname}_sample_count"] = str(len(values))
            else:
                result[fieldname] = str(group[0].get(fieldname, ""))
                if fieldname in SUCCESS_DEPENDENT_METRICS:
                    result[f"{fieldname}_sample_count"] = "0"
        aggregated.append(result)
    return aggregated


def _fixed_user_methods(
    seed_rows: Sequence[dict[str, str]],
    aggregated_rows: Sequence[dict[str, str]],
) -> list[dict[str, object]]:
    methods: list[dict[str, object]] = []
    for aggregated in aggregated_rows:
        method_key = aggregated.get("method", "")
        records = [
            dict(row)
            for row in seed_rows
            if row.get("method", "") == method_key
        ]
        method: dict[str, object] = dict(aggregated)
        method["is_system"] = str(method.get("is_system", "")).lower() in {
            "1",
            "true",
            "yes",
        }
        method["seed_metrics"] = records
        method["training_history_paths"] = [
            str(row["training_history"])
            for row in records
            if row.get("training_history")
        ]
        methods.append(method)
    return methods


def _plot_fixed_user_seed_summary(
    user_dir: Path,
    seed_rows: Sequence[dict[str, str]],
    aggregated_rows: Sequence[dict[str, str]],
    output_suffix: str = "",
) -> list[Path]:
    from scripts.compare_system_baselines import (
        plot_delay_energy_tradeoff,
        plot_method_comparison,
        plot_paper_dashboard,
        plot_performance_radar,
        plot_success_continuity_scatter,
        plot_training_curve_vs_baselines,
    )

    methods = _fixed_user_methods(seed_rows, aggregated_rows)
    generated: list[Path] = []
    plotters = (
        lambda: plot_method_comparison(
            methods,
            user_dir,
            output_suffix=output_suffix,
        ),
        lambda: plot_training_curve_vs_baselines(
            None,
            methods,
            user_dir,
            window=5,
            output_suffix=output_suffix,
        ),
        lambda: plot_paper_dashboard(
            None,
            methods,
            user_dir,
            window=5,
            output_suffix=output_suffix,
        ),
        lambda: plot_delay_energy_tradeoff(
            methods,
            user_dir,
            output_suffix=output_suffix,
        ),
        lambda: plot_success_continuity_scatter(
            methods,
            user_dir,
            output_suffix=output_suffix,
        ),
        lambda: plot_performance_radar(
            methods,
            user_dir,
            output_suffix=output_suffix,
        ),
    )
    for plotter in plotters:
        path = plotter()
        if path is not None:
            generated.append(path)
    return generated


def aggregate_user_summaries(
    suite_dir: Path,
    user_counts: Sequence[int],
    include_methods: Sequence[str] = (),
    output_suffix: str = "",
    seeds: Sequence[int] = (),
) -> tuple[list[dict[str, str]], Path]:
    seed_values = tuple(seeds) or (42,)
    seed_rows: list[dict[str, str]] = []
    expected_reward_config: Optional[tuple[float, ...]] = None
    for num_users in user_counts:
        user_seed_rows: list[dict[str, str]] = []
        for seed in seed_values:
            user_dir = suite_dir / f"u{num_users}"
            compare_dir = (
                user_dir / f"seed_{seed}"
                if len(seed_values) > 1
                else user_dir
            )
            summary_csv = compare_dir / "comparison_summary.csv"
            if not summary_csv.exists():
                raise FileNotFoundError(f"Missing comparison summary: {summary_csv}")
            reward_config = _validate_comparison_schema(compare_dir)
            if expected_reward_config is None:
                expected_reward_config = reward_config
            elif reward_config != expected_reward_config:
                raise ValueError(
                    f"{compare_dir} uses reward configuration {reward_config}, "
                    f"but the suite requires {expected_reward_config}."
                )
            user_seed_rows.extend(
                row
                for row in _read_comparison_rows(summary_csv, num_users, seed)
                if method_matches_include(row, include_methods)
            )
        seed_rows.extend(user_seed_rows)
        aggregated_user_rows = _aggregate_seed_rows(user_seed_rows)
        _write_csv(
            suite_dir / f"u{num_users}" / "comparison_seed_records.csv",
            user_seed_rows,
        )
        _write_csv(
            suite_dir / f"u{num_users}" / "comparison_summary.csv",
            aggregated_user_rows,
        )
        _plot_fixed_user_seed_summary(
            suite_dir / f"u{num_users}",
            user_seed_rows,
            aggregated_user_rows,
            output_suffix=output_suffix,
        )
    if include_methods and not seed_rows:
        raise ValueError(
            "No methods matched --include-methods: "
            f"{', '.join(include_methods)}"
        )

    rows = _aggregate_seed_rows(seed_rows)
    _write_csv(
        suite_dir / suffixed_filename("multiuser_seed_records.csv", output_suffix),
        seed_rows,
    )
    output_csv = suite_dir / suffixed_filename("multiuser_summary.csv", output_suffix)
    _write_csv(output_csv, rows)
    return rows, output_csv


def _float_or_none(value: object) -> Optional[float]:
    try:
        if value is None or value == "":
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _method_order(rows: Sequence[dict[str, str]]) -> list[str]:
    preferred = list(METHOD_DISPLAY_NAMES.values())
    present = {row.get("display_name", "") for row in rows}
    ordered = [name for name in preferred if name in present]
    ordered.extend(sorted(name for name in present if name and name not in ordered))
    return ordered


def _apply_service_continuity_zoom(
    ax,
    rows: Sequence[dict[str, str]],
    method_names: Sequence[str],
    metric_key: str,
    scale: float,
) -> None:
    if metric_key != "service_continuity_rate":
        return

    values_by_method: dict[str, list[float]] = {}
    for display_name in method_names:
        values = [
            float(row[metric_key]) * scale
            for row in rows
            if row.get("display_name") == display_name
            and _float_or_none(row.get(metric_key)) is not None
        ]
        if values:
            values_by_method[display_name] = values

    all_values = [value for values in values_by_method.values() for value in values]
    high_values = [value for value in all_values if value >= 80.0]
    if len(high_values) < 2:
        return

    high_min = min(high_values)
    high_max = max(high_values)
    y_min = max(0.0, high_min - 2.5)
    y_max = min(100.5, high_max + 1.0)
    if y_max - y_min < 8.0:
        y_min = max(0.0, y_max - 8.0)

    clipped = {
        name: values
        for name, values in values_by_method.items()
        if min(values) < y_min
    }
    if not clipped:
        return

    ax.set_ylim(y_min, y_max)
    ax.text(
        0.02,
        0.04,
        "Zoomed y-axis",
        transform=ax.transAxes,
        ha="left",
        va="bottom",
        fontsize=8.5,
        color="#333333",
        bbox={
            "boxstyle": "round,pad=0.25",
            "facecolor": "white",
            "edgecolor": "#999999",
            "alpha": 0.82,
        },
    )
    inset = ax.inset_axes([0.10, 0.13, 0.38, 0.30])
    lines_by_label = {line.get_label(): line for line in ax.get_lines()}
    low_min = min(min(values) for values in clipped.values())
    low_max = max(max(values) for values in clipped.values())
    low_margin = max((low_max - low_min) * 0.20, 1.0)
    for display_name, values in clipped.items():
        method_rows = [
            row for row in rows
            if row.get("display_name") == display_name
            and _float_or_none(row.get(metric_key)) is not None
        ]
        method_rows.sort(key=lambda row: int(row["num_users"]))
        x_values = [int(row["num_users"]) for row in method_rows]
        line = lines_by_label.get(display_name)
        inset.plot(
            x_values,
            values,
            marker=line.get_marker() if line is not None else "o",
            color=line.get_color() if line is not None else None,
            linewidth=1.4,
            markersize=3.0,
            label=display_name,
        )
    inset.set_title("Below-axis methods", fontsize=7.5, pad=2)
    inset.set_ylim(max(0.0, low_min - low_margin), min(100.0, low_max + low_margin))
    inset.set_xticks(sorted({int(row["num_users"]) for row in rows})[::2])
    inset.tick_params(axis="both", labelsize=7, length=2)
    inset.grid(True, alpha=0.25, linestyle="--", linewidth=0.6)
    inset.set_facecolor("white")
    for spine in inset.spines.values():
        spine.set_edgecolor("#888888")
        spine.set_linewidth(0.8)
    mark_kwargs = {
        "transform": ax.transAxes,
        "color": "#333333",
        "clip_on": False,
        "linewidth": 1.0,
    }
    ax.plot((-0.012, 0.012), (-0.015, 0.015), **mark_kwargs)
    ax.plot((0.988, 1.012), (-0.015, 0.015), **mark_kwargs)


def setup_plot_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "DejaVu Serif"],
            "font.size": 11,
            "axes.titlesize": 12,
            "axes.labelsize": 11,
            "legend.fontsize": 9,
            "lines.linewidth": 1.8,
            "lines.markersize": 5,
            "figure.dpi": 220,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
            "axes.grid": True,
            "grid.alpha": 0.45,
            "grid.linestyle": "--",
        }
    )


def plot_scaling_metrics(
    rows: Sequence[dict[str, str]],
    suite_dir: Path,
    metric_specs: Sequence[tuple[str, str, str, float]],
    filename: str,
    output_suffix: str = "",
) -> Optional[Path]:
    if not rows:
        return None
    setup_plot_style()
    cols = 2
    metric_count = len(metric_specs)
    rows_count = (metric_count + cols - 1) // cols
    fig, axes = plt.subplots(rows_count, cols, figsize=(11, 4.2 * rows_count), squeeze=False)
    method_names = _method_order(rows)
    markers = ["o", "s", "^", "D", "v", "P", "X", "*", "h"]

    for ax, (metric_key, title, ylabel, scale) in zip(axes.flat, metric_specs):
        for index, display_name in enumerate(method_names):
            method_rows = [
                row for row in rows
                if row.get("display_name") == display_name and _float_or_none(row.get(metric_key)) is not None
            ]
            method_rows.sort(key=lambda row: int(row["num_users"]))
            if not method_rows:
                continue
            x_values = [int(row["num_users"]) for row in method_rows]
            y_values = [float(row[metric_key]) * scale for row in method_rows]
            ci_lows = [
                _float_or_none(row.get(f"{metric_key}_ci_low"))
                for row in method_rows
            ]
            ci_highs = [
                _float_or_none(row.get(f"{metric_key}_ci_high"))
                for row in method_rows
            ]
            line = ax.plot(
                x_values,
                y_values,
                marker=markers[index % len(markers)],
                label=display_name,
            )[0]
            if all(value is not None for value in ci_lows + ci_highs):
                ax.fill_between(
                    x_values,
                    [float(value) * scale for value in ci_lows],
                    [float(value) * scale for value in ci_highs],
                    color=line.get_color(),
                    alpha=0.14,
                )
        ax.set_title(title)
        ax.set_xlabel("Number of Users")
        ax.set_ylabel(ylabel)
        ax.set_xticks(sorted({int(row["num_users"]) for row in rows}))
        _apply_service_continuity_zoom(ax, rows, method_names, metric_key, scale)

    for ax in axes.flat[metric_count:]:
        ax.axis("off")

    handles, labels = axes.flat[0].get_legend_handles_labels()
    if handles:
        if rows_count == 1:
            fig.legend(
                handles,
                labels,
                loc="upper center",
                bbox_to_anchor=(0.5, 1.06),
                ncol=min(5, len(labels)),
                frameon=True,
            )
            fig.subplots_adjust(top=0.76)
        else:
            fig.legend(handles, labels, loc="upper center", ncol=min(5, len(labels)), frameon=True)
            fig.subplots_adjust(top=0.88)
    output_path = suite_dir / suffixed_filename(filename, output_suffix)
    fig.savefig(output_path)
    plt.close(fig)
    return output_path


def _load_training_curve(history_path: Path) -> tuple[list[float], list[float]]:
    if not history_path.exists():
        return [], []
    with history_path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    steps: list[float] = []
    rewards: list[float] = []
    for record in payload.get("training", []):
        reward = _float_or_none(record.get("mean_reward", record.get("reward")))
        step = _float_or_none(record.get("total_steps", record.get("step")))
        if reward is None or step is None:
            continue
        steps.append(step)
        rewards.append(reward)
    return steps, rewards


def training_history_path(paths: SuitePaths, method: str) -> Path:
    if method == "han_mappo":
        return paths.system_run_dir / "training_history.json"
    return paths.compare_output_dir / "learned_baselines" / method / "training_history.json"


def _aggregate_training_curves(
    history_paths: Sequence[Path],
) -> tuple[list[float], list[float], list[float], list[float]]:
    curves: list[tuple[list[float], list[float]]] = []
    for path in history_paths:
        steps, rewards = _load_training_curve(path)
        if steps:
            curves.append((steps, rewards))
    if not curves:
        return [], [], [], []

    common_steps = sorted(
        set(curves[0][0]).intersection(*(set(steps) for steps, _ in curves[1:]))
    )
    if not common_steps:
        return [], [], [], []
    reward_maps = [
        {step: reward for step, reward in zip(steps, rewards)}
        for steps, rewards in curves
    ]
    means: list[float] = []
    lows: list[float] = []
    highs: list[float] = []
    for step in common_steps:
        values = [reward_map[step] for reward_map in reward_maps]
        mean, low, high = bootstrap_mean_ci(values)
        means.append(mean)
        lows.append(low)
        highs.append(high)
    return common_steps, means, lows, highs


def plot_reward_convergence(
    project_root: Path,
    run_id: str,
    user_counts: Sequence[int],
    suite_dir: Path,
    seeds: Sequence[int] = (42,),
    include_methods: Sequence[str] = (),
    output_suffix: str = "",
) -> Optional[Path]:
    setup_plot_style()
    fig, axes = plt.subplots(1, len(user_counts), figsize=(5.2 * len(user_counts), 4.2), squeeze=False)
    plotted_any = False
    markers = ["o", "s", "^", "D", "v"]

    for axis_index, num_users in enumerate(user_counts):
        ax = axes.flat[axis_index]
        reward_methods = [
            method
            for method in LEARNED_REWARD_METHODS
            if method_matches_include(
                {"method": method, "display_name": method_display_name(method)},
                include_methods,
            )
        ]
        for method_index, method in enumerate(reward_methods):
            history_paths = [
                training_history_path(
                    build_paths(
                        project_root,
                        run_id,
                        num_users,
                        seed=seed,
                        multi_seed=len(seeds) > 1,
                    ),
                    method,
                )
                for seed in seeds
            ]
            steps, rewards, ci_lows, ci_highs = _aggregate_training_curves(
                history_paths
            )
            if not steps:
                continue
            plotted_any = True
            line = ax.plot(
                steps,
                rewards,
                marker=markers[method_index % len(markers)],
                markevery=max(len(steps) // 8, 1),
                label=method_display_name(method),
            )[0]
            if len(history_paths) > 1:
                ax.fill_between(
                    steps,
                    ci_lows,
                    ci_highs,
                    color=line.get_color(),
                    alpha=0.14,
                )
        ax.set_title(f"U{num_users}")
        ax.set_xlabel("Training Steps")
        ax.set_ylabel("Mean Episode Reward")

    handles, labels = axes.flat[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="upper center", ncol=min(5, len(labels)), frameon=True)
        fig.subplots_adjust(top=0.82)

    if not plotted_any:
        plt.close(fig)
        return None
    output_path = suite_dir / suffixed_filename("multiuser_reward_convergence.png", output_suffix)
    fig.savefig(output_path)
    plt.close(fig)
    return output_path


def write_manifest(
    suite_dir: Path,
    config: MultiUserConfig,
    generated_paths: Iterable[Path],
) -> Path:
    manifest_path = suite_dir / suffixed_filename("suite_manifest.json", config.output_suffix)
    payload = {
        "run_id": config.run_id,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "config": asdict(config),
        "method_display_names": METHOD_DISPLAY_NAMES,
        "generated_artifacts": [str(path) for path in generated_paths],
    }
    with manifest_path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
    return manifest_path


def generate_aggregate_artifacts(
    project_root: Path,
    config: MultiUserConfig,
    suite_dir: Path,
) -> list[Path]:
    summary_rows, summary_csv = aggregate_user_summaries(
        suite_dir,
        config.user_counts,
        include_methods=config.include_methods,
        output_suffix=config.output_suffix,
        seeds=effective_seeds(config),
    )
    generated: list[Path] = [summary_csv]

    reward_plot = plot_reward_convergence(
        project_root,
        config.run_id,
        config.user_counts,
        suite_dir,
        seeds=effective_seeds(config),
        include_methods=config.include_methods,
        output_suffix=config.output_suffix,
    )
    if reward_plot is not None:
        generated.append(reward_plot)
    core_plot = plot_scaling_metrics(
        summary_rows,
        suite_dir,
        CORE_SCALING_METRICS,
        "multiuser_core_metrics.png",
        output_suffix=config.output_suffix,
    )
    if core_plot is not None:
        generated.append(core_plot)
    resource_plot = plot_scaling_metrics(
        summary_rows,
        suite_dir,
        RESOURCE_SCALING_METRICS,
        "multiuser_resource_metrics.png",
        output_suffix=config.output_suffix,
    )
    if resource_plot is not None:
        generated.append(resource_plot)
    combined_plot = plot_scaling_metrics(
        summary_rows,
        suite_dir,
        COMBINED_SCALING_METRICS,
        "multiuser_combined_metrics.png",
        output_suffix=config.output_suffix,
    )
    if combined_plot is not None:
        generated.append(combined_plot)
    manifest = write_manifest(suite_dir, config, generated)
    generated.append(manifest)
    return generated


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run user-count scaling experiments for HAN+MAPPO and comparison baselines."
    )
    parser.add_argument("--run-id", type=str, default=None)
    parser.add_argument("--user-counts", type=int, nargs="+", default=list(DEFAULT_USER_COUNTS))
    parser.add_argument("--python-executable", type=str, default=DEFAULT_PYTHON)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--seeds",
        type=int,
        nargs="+",
        default=[],
        help="Independent training seeds. When omitted, --seed is used for backward compatibility.",
    )
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--total-timesteps", type=int, default=300_000)
    parser.add_argument("--max-steps", type=int, default=600)
    parser.add_argument("--n-steps", type=int, default=1024)
    parser.add_argument("--eval-interval", type=int, default=50_000)
    parser.add_argument("--eval-episodes", type=int, default=3)
    parser.add_argument("--save-interval", type=int, default=100_000)
    parser.add_argument(
        "--graph-update-interval",
        "--graph_update_interval",
        dest="graph_update_interval",
        type=int,
        default=1,
    )
    parser.add_argument("--compare-episodes", type=int, default=3)
    parser.add_argument("--plot-window", type=int, default=5)
    parser.add_argument("--early-stop-patience", type=int, default=0)
    parser.add_argument("--best-model-metric", type=str, default="avg_delay")
    parser.add_argument("--compare-ranking-metric", type=str, default="avg_delay")
    parser.add_argument("--baselines", nargs="+", default=list(DEFAULT_BASELINES))
    parser.add_argument("--force-system-train", action="store_true")
    parser.add_argument("--skip-system-train", action="store_true")
    parser.add_argument("--skip-compare", action="store_true")
    parser.add_argument("--reuse-learned-checkpoints", action="store_true")
    parser.add_argument(
        "--include-methods",
        nargs="+",
        default=[],
        help=(
            "Only include these method names when rebuilding aggregate CSV and figures "
            "from existing comparison summaries, e.g. han_mappo mappo_no_han random."
        ),
    )
    parser.add_argument(
        "--output-suffix",
        type=str,
        default="",
        help=(
            "Append this suffix before aggregate artifact extensions, e.g. "
            "--output-suffix selected writes multiuser_core_metrics_selected.png."
        ),
    )
    parser.add_argument(
        "--aggregate-only",
        action="store_true",
        help="Only rebuild suite-level CSV, figures, and manifest from existing u*/comparison_summary.csv files.",
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args(argv)


def config_from_args(args: argparse.Namespace) -> MultiUserConfig:
    return MultiUserConfig(
        run_id=resolve_run_id(args.run_id),
        user_counts=tuple(args.user_counts),
        python_executable=args.python_executable,
        seed=args.seed,
        seeds=tuple(args.seeds),
        device=args.device,
        total_timesteps=args.total_timesteps,
        max_steps=args.max_steps,
        n_steps=args.n_steps,
        eval_interval=args.eval_interval,
        eval_episodes=args.eval_episodes,
        save_interval=args.save_interval,
        graph_update_interval=args.graph_update_interval,
        best_model_metric=args.best_model_metric,
        compare_ranking_metric=args.compare_ranking_metric,
        compare_episodes=args.compare_episodes,
        plot_window=args.plot_window,
        early_stop_patience=args.early_stop_patience,
        baselines=tuple(args.baselines),
        skip_system_train=args.skip_system_train,
        skip_compare=args.skip_compare,
        force_system_train=args.force_system_train,
        reuse_learned_checkpoints=args.reuse_learned_checkpoints,
        aggregate_only=args.aggregate_only,
        include_methods=tuple(getattr(args, "include_methods", [])),
        output_suffix=normalize_output_suffix(getattr(args, "output_suffix", "")),
        dry_run=args.dry_run,
    )


def run_user_count(
    config: MultiUserConfig,
    num_users: int,
    seed: Optional[int] = None,
) -> SuitePaths:
    seeds = effective_seeds(config)
    run_seed = config.seed if seed is None else seed
    paths = build_paths(
        PROJECT_ROOT,
        config.run_id,
        num_users,
        seed=run_seed,
        multi_seed=len(seeds) > 1,
    )
    if not config.dry_run:
        paths.log_dir.mkdir(parents=True, exist_ok=True)
        paths.suite_dir.mkdir(parents=True, exist_ok=True)
        paths.compare_output_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n=== Multi-user scaling: U{num_users}, seed {run_seed} ===")
    print(f"System run dir: {paths.system_run_dir}")
    print(f"Compare output dir: {paths.compare_output_dir}")

    train_needed = not config.skip_system_train
    complete_training = has_training_artifacts(
        paths.system_run_dir,
        config=config,
        num_users=num_users,
        seed=run_seed,
    )
    if train_needed and complete_training and not config.force_system_train:
        train_needed = False
        print("Complete HAN+MAPPO artifacts found; reusing system training.")
    elif (
        train_needed
        and has_any_training_artifacts(paths.system_run_dir)
        and not config.force_system_train
    ):
        raise RuntimeError(
            f"Incomplete or configuration-mismatched training artifacts found in "
            f"{paths.system_run_dir}. Use a new --run-id, or explicitly pass "
            "--force-system-train to restart this run."
        )

    if train_needed:
        if not config.dry_run:
            paths.system_run_dir.mkdir(parents=True, exist_ok=True)
        run_command(
            build_train_command(paths, config, num_users, seed=run_seed),
            PROJECT_ROOT,
            paths.suite_dir / f"u{num_users}_seed{run_seed}_system_train.log",
            config.dry_run,
        )
    else:
        print("System training step skipped.")

    if not config.skip_compare:
        if (
            not config.dry_run
            and not has_training_artifacts(
                paths.system_run_dir,
                config=config,
                num_users=num_users,
                seed=run_seed,
            )
        ):
            raise FileNotFoundError(
                f"No complete, configuration-matched HAN+MAPPO training found in "
                f"{paths.system_run_dir}. Run without --skip-system-train first."
            )
        run_command(
            build_compare_command(paths, config, num_users, seed=run_seed),
            PROJECT_ROOT,
            paths.suite_dir / f"u{num_users}_seed{run_seed}_compare.log",
            config.dry_run,
        )
    else:
        print("Comparison step skipped.")
    return paths


def main() -> None:
    config = config_from_args(parse_args())
    print(f"Run id: {config.run_id}")
    print(f"User counts: {', '.join(str(count) for count in config.user_counts)}")
    print(f"Seeds: {', '.join(str(seed) for seed in effective_seeds(config))}")
    print(f"Baselines: {', '.join(config.baselines)}")
    if config.include_methods:
        print(f"Included methods: {', '.join(config.include_methods)}")
    if config.output_suffix:
        print(f"Output suffix: {config.output_suffix}")

    suite_dir = build_paths(PROJECT_ROOT, config.run_id, config.user_counts[0]).suite_dir
    if config.aggregate_only:
        generated = generate_aggregate_artifacts(PROJECT_ROOT, config, suite_dir)
        summary_csv = suite_dir / suffixed_filename("multiuser_summary.csv", config.output_suffix)
        print(f"Multi-user summary CSV: {summary_csv}")
        for artifact in generated:
            print(f"Generated artifact: {artifact}")
        return

    first_paths: Optional[SuitePaths] = None
    for num_users in config.user_counts:
        for seed in effective_seeds(config):
            paths = run_user_count(config, num_users, seed=seed)
            first_paths = first_paths or paths

    if config.dry_run or config.skip_compare:
        print("Aggregation skipped.")
        return

    assert first_paths is not None
    generated = generate_aggregate_artifacts(PROJECT_ROOT, config, first_paths.suite_dir)
    summary_csv = first_paths.suite_dir / suffixed_filename("multiuser_summary.csv", config.output_suffix)

    print(f"Multi-user summary CSV: {summary_csv}")
    for artifact in generated:
        print(f"Generated artifact: {artifact}")


if __name__ == "__main__":
    main()
